routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Site\ProfileController;
use App\Http\Controllers\Site\UserAlbumController;
use App\Http\Controllers\Site\SiteController;
use App\Http\Controllers\Board\BoardController;
use App\Http\Controllers\Board\AdminAuthController;
use App\Http\Controllers\Board\RoleController;
use App\Http\Controllers\Board\AdminController;
use App\Http\Controllers\Board\UserController;
use App\Http\Controllers\Board\AlbumController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


require __DIR__.'/auth.php';

Route::get('/' , [SiteController::class , 'index'] );
Route::get('/album/{album}' , [SiteController::class , 'album'] )->name('albums.show');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/profile' , [ProfileController::class , 'index'])->name('profile.show');
    Route::patch('/profile' , [ProfileController::class , 'update'])->name('profile.update');
    Route::patch('/password' , [ProfileController::class , 'update_password'])->name('password.update');
    Route::get('/albums' , [UserAlbumController::class , 'index'] )->name('user.albums.index');
    Route::get('/albums/create' , [UserAlbumController::class , 'create'] )->name('user.albums.create');
    Route::post('/albums' , [UserAlbumController::class , 'store'] )->name('user.albums.store');
    Route::get('/albums/{album}' , [UserAlbumController::class , 'show'] )->name('user.albums.show');
    Route::delete('/albums/{album}' , [UserAlbumController::class , 'destroy'] )->name('user.albums.destroy');
    Route::patch('/albums/{album}' , [UserAlbumController::class , 'update'] )->name('user.albums.update');

    Route::delete('/albums/{album}/images/{image}',[UserAlbumController::class , 'destroy_image'])->name('user.albums.images.destroy');
    Route::patch('/albums/{album}/images/{image}',[UserAlbumController::class , 'update_image'])->name('user.albums.images.update');
    Route::post('/albums/{album}/images',[UserAlbumController::class , 'store_images'])->name('user.albums.images.store');
});


Route::group(['prefix' => 'Board' , 'as' => 'board.' ], function() {
    Route::get('/login' , [AdminAuthController::class  , 'index'] );
    Route::post('/login' , [AdminAuthController::class  , 'login'] )->name('login');
    Route::group(['middleware' => 'admin'], function() {
        Route::get('/' , [BoardController::class  , 'index'] )->name('home');
        Route::resource('roles', RoleController::class);
        Route::resource('admins', AdminController::class);
        Route::get('/users' , [UserController::class , 'index' ] )->name('users.index');
        Route::get('/users/{user}' , [UserController::class , 'show' ] )->name('users.show');
        Route::get('/albums' , [AlbumController::class , 'index' ] )->name('albums.index');
        Route::get('/albums/{album}' , [AlbumController::class , 'show' ] )->name('albums.show');
        Route::delete('images/{image}' ,  [AlbumController::class , 'delete_image' ] )->name('images.destroy');
    });
});

app/Http/Controllers/Board/AdminAuthController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\Http\Requests\Board\LoginRequest;
class AdminAuthController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('board.login');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function login(LoginRequest $request)
    {
        $credentials = $request->only('email' , 'password');

        if (Auth::guard('admin')->attempt($credentials)) {
            $request->session()->regenerate();

            return redirect(route('board.home'));
        }

        return back()->with('error' , 'we could not find this admin , please try again ' );
    }
}

app/Http/Controllers/Board/AdminController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\Admin;
use App\Http\Requests\Board\Admins\StoreAdminRequest;
use App\Http\Requests\Board\Admins\UpdateAdminRequest;
class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $this->authorize('viewAny',Admin::class);
        return view('board.admins.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create',Admin::class);

        $roles = Role::all();
        return view('board.admins.create' , compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminRequest $request)
    {
        $this->authorize('create',Admin::class);

        $admin = new Admin;
        if(!$admin->add($request))
            return back()->with('error' , 'Error , try again ' );

        return back()->with('success' , 'Admin Added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Admin $admin)
    {
        $this->authorize('view',Admin::class);

        $admin->load('role');
        return view('board.admins.show' , compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Admin $admin)
    {
        $this->authorize('update',Admin::class);

        $roles = Role::all();
        return view('board.admins.edit' , compact('roles' , 'admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdminRequest $request, Admin $admin)
    {
        $this->authorize('update',Admin::class);

        if(!$admin->edit($request))
            return back()->with('error' , 'Error , try again ' );

        return back()->with('success' , 'Admin updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Admin $admin)
    {
        $this->authorize('delete',Admin::class);

        if(!$admin->remove())
            return back()->with('error' , 'Error , try again ' );

        return back()->with('success' , 'Admin deleted successfully');
    }
}

app/Http/Controllers/Board/AlbumController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Album;
use App\Models\AlbumImage;
use Storage;
class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny',Album::class);
        return view('board.albums.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {
        $this->authorize('view',Album::class);
        $album->load('images');
        return view('board.albums.show' , compact('album') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete_image(AlbumImage $image)
    {
        $this->authorize('delete',Album::class);

        Storage::delete(['albums/'.$image->image]);
        $image->delete();
        return back()->with('success' , 'image deleted successfully');
    }
}

app/Http/Controllers/Board/BoardController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BoardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('board.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Board/RoleController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Role;
use App\Http\Requests\Board\Roles\StoreRoleRequest;
use App\Http\Requests\Board\Roles\UpdateRoleRequest;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny',Role::class);

        return view('board.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create',Role::class);

        return view('board.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRoleRequest $request)
    {
        $this->authorize('create',Role::class);

        $role = new Role;
        if(!$role->add($request))
            return back()->with('error' , 'Error , try again ' );

        return back()->with('success' , 'Role Added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        $this->authorize('view',Role::class);

        $role->load(['permissions' , 'admin']);
        return view('board.roles.show' , compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {

        $this->authorize('update',Role::class);

        $permissions = $role->permissions()->pluck('permission')->toArray();
        return view('board.roles.edit' , compact('role' , 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, Role $role)
    {
        $this->authorize('update',Role::class);

        if(!$role->edit($request))
            return back()->with('error' , 'Error , try again ' );

        return back()->with('success' , 'Role Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->authorize('delete',Role::class);

        if(!$role->remove())
            return back()->with('error' , 'Error , try again ' );

        return back()->with('success' , 'Role deleted successfully');
    }
}

app/Http/Controllers/Board/UserController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('board.users.index');
    }

    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $user->load('albums');
        return view('board.users.show' , compact('user'));
    }
}

app/Http/Livewire/Board/Admins/ListAllAdmins.php
<?php

namespace App\Http\Livewire\Board\Admins;

use Livewire\Component;
use App\Models\Admin;
use Livewire\WithPagination;
class ListAllAdmins extends Component
{
    use WithPagination;
    public $search = '';
    public $rows = 10;

    protected $paginationTheme = 'bootstrap';

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function updatingRows()
    {
        $this->resetPage();
    }

    public function render()
    {
        $admins = Admin::query();
        if($this->search != '')
            $admins->where('name' ,'like', '%'.$this->search.'%' )->orWhere('email' ,'like', '%'.$this->search.'%' );

        $admins = $admins->latest()->paginate($this->rows);
        return view('livewire.board.admins.list-all-admins' , compact('admins'));
    }
}

app/Http/Livewire/Board/Albums/ListAllAlbums.php
<?php

namespace App\Http\Livewire\Board\Albums;

use Livewire\Component;
use App\Models\Album;
use Livewire\WithPagination;
class ListAllAlbums extends Component
{
    use WithPagination;
    public $search = '';
    public $rows = 10;

    protected $paginationTheme = 'bootstrap';

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function updatingRows()
    {
        $this->resetPage();
    }

    public function render()
    {
        $albums = Album::query();
        if($this->search != '')
            $albums->where('name' ,'like', '%'.$this->search.'%' );

        $albums = $albums->latest()->paginate($this->rows);
        return view('livewire.board.albums.list-all-albums' , compact('albums'));
    }
}

app/Http/Livewire/Board/Roles/ListAllRoles.php
<?php

namespace App\Http\Livewire\Board\Roles;

use Livewire\Component;
use App\Models\Role;
use Livewire\WithPagination;
class ListAllRoles extends Component
{
    use WithPagination;
    public $search = '';
    public $rows = 10;

    protected $paginationTheme = 'bootstrap';

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function updatingRows()
    {
        $this->resetPage();
    }

    public function render()
    {
        $roles = Role::query()->with('admin');
        if($this->search != '')
            $roles->where('name' ,'like', '%'.$this->search.'%' );

        $roles = $roles->latest()->paginate($this->rows);
        return view('livewire.board.roles.list-all-roles' , compact('roles'));
    }
}

app/Http/Livewire/Board/Users/ListAllUsers.php
<?php

namespace App\Http\Livewire\Board\Users;

use Livewire\Component;
use App\Models\User;
use Livewire\WithPagination;
class ListAllUsers extends Component
{
    use WithPagination;
    public $search = '';
    public $rows = 10;

    protected $paginationTheme = 'bootstrap';

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function updatingRows()
    {
        $this->resetPage();
    }

    public function render()
    {
        $users = User::query();
        if($this->search != '')
            $users->where('name' ,'like', '%'.$this->search.'%' )->orWhere('email' ,'like', '%'.$this->search.'%' );

        $users = $users->latest()->paginate($this->rows);
        return view('livewire.board.users.list-all-users' , compact('users'));
    }
}

resources/views/board/admins/create.blade.php
@extends('board.layouts.master')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Admins </h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ route('board.home') }}">Home</a></li>
					<li class="breadcrumb-item"><a href="{{ route('board.admins.index') }}">Admins</a></li>
					<li class="breadcrumb-item active">Add new Admin</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				@include('site.layouts.messages')
				<!-- general form elements -->
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">Add new Admin</h3>
					</div>
					<!-- /.card-header -->
					<!-- form start -->
					<form action="{{ route('board.admins.store') }}" method="POST" >
						@csrf
						<div class="card-body">
							<div class="form-group">
								<label for="exampleInputEmail1">name </label>
								<input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter  name ">
								@error('name')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1">email </label>
								<input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email ">
								@error('email')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1">Password  </label>
								<input type="password" name="password" class="form-control" id="exampleInputEmail1" placeholder="Enter password ">
								@error('password')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1"> password confirmation </label>
								<input type="password" name="password_confirmation" class="form-control" id="exampleInputEmail1" placeholder="Enter password confirmation ">
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1"> Role </label>
								<select name="role_id" class="form-control" required="required">
									@foreach ($roles as $role)
										<option value="{{ $role->id }}"> {{ $role->name }} </option>
									@endforeach
								</select>
								@error('role_id')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							
						</div>
						<!-- /.card-body -->

						<div class="card-footer">
							<button type="submit" class="btn btn-primary">Add </button>
						</div>
					</form>
				</div>
				<!-- /.card -->
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/board/admins/edit.blade.php
@extends('board.layouts.master')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Admins </h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ route('board.home') }}">Home</a></li>
					<li class="breadcrumb-item"><a href="{{ route('board.admins.index') }}">Admins</a></li>
					<li class="breadcrumb-item active">Edit  Admin</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				@include('site.layouts.messages')
				<!-- general form elements -->
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">Edit Admin</h3>
					</div>
					<!-- /.card-header -->
					<!-- form start -->
					<form action="{{ route('board.admins.update' , ['admin' => $admin->id] ) }}" method="POST" >
						@csrf
						@method('PATCH')
						<div class="card-body">
							<div class="form-group">
								<label for="exampleInputEmail1">name * </label>
								<input type="text" name="name"  value="{{ $admin->name }}" class="form-control" id="exampleInputEmail1" placeholder="Enter  name ">
								@error('name')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1">email *</label>
								<input type="email" name="email" value="{{ $admin->email }}"  class="form-control" id="exampleInputEmail1" placeholder="Enter email ">
								@error('email')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1">new Password  </label>
								<input type="password" name="password" class="form-control" id="exampleInputEmail1" placeholder="Enter password ">
								@error('password')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1"> new password confirmation </label>
								<input type="password" name="password_confirmation" class="form-control" id="exampleInputEmail1" placeholder="Enter password confirmation ">
							</div>
							<div class="form-group">
								<label for="exampleInputEmail1"> Role *</label>
								<select name="role_id" class="form-control" required="required">
									@foreach ($roles as $role)
										<option value="{{ $role->id }}" {{ $admin->role_id == $role->id ? 'selected="selected"' : '' }} > {{ $role->name }} </option>
									@endforeach
								</select>
								@error('role_id')
								<p class='text-danger' >{{ $message }}</p>
								@enderror
							</div>
							
						</div>
						<!-- /.card-body -->

						<div class="card-footer">
							<button type="submit" class="btn btn-warning"> Edit </button>
						</div>
					</form>
				</div>
				<!-- /.card -->
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/board/admins/index.blade.php
@extends('board.layouts.master')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Admins</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ route('board.home') }}">Home</a></li>
					<li class="breadcrumb-item active">Admins</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				@include('site.layouts.messages')
				<!-- general form elements -->
				@livewire('board.admins.list-all-admins')
				<!-- /.card -->
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/board/admins/show.blade.php
@extends('board.layouts.master')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Admins</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ route('board.home') }}">Home</a></li>
					<li class="breadcrumb-item"> <a href="{{ route('board.admins.index') }}">Admins</a> </li>
					<li class="breadcrumb-item active">Show Admin details</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				@include('site.layouts.messages')
				<!-- general form elements -->
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">Show Admin Details</h3>
					</div>
					<table class="table table-bordered table-hover">
						<tbody>
							<tr>
								<th> Date </th>
								<td> {{ $admin->created_at->toDayDateTimeString() }} <span class='text-muted' > {{ $admin->created_at->diffForHumans() }} </span> </td>
							</tr>
							<tr>
								<th>Role</th>
								<td>{{ optional($admin->role)->name }}</td>
							</tr>
							<tr>
								<th> name</th>
								<td>{{ $admin->name }}</td>
							</tr>
							<tr>
								<th> email </th>
								<td>{{ $admin->email }}</td>
							</tr>

						</tbody>
					</table>
					
				</div>
				<!-- /.card -->
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection